#!/usr/bin/env python3
"""Byte differences between the original ROM and a patched build, as C.

usage: romdiff.py BASE.md PATCHED.md OUT.c

The port loads the user's original ROM and applies these runs in memory, so
code added by source overlays (and any data it reads) is present at run time.
Overlays must preserve sizes: a build whose original bytes moved is refused,
since the runs would then contain game data.
"""
import sys

MAX_CHANGED = 16384


def main():
    base = open(sys.argv[1], "rb").read()
    patched = open(sys.argv[2], "rb").read()
    if len(base) != len(patched):
        sys.exit("romdiff: sizes differ")
    diff = [i for i in range(len(base)) if base[i] != patched[i]]
    if len(diff) > MAX_CHANGED:
        sys.exit(f"romdiff: {len(diff)} bytes changed; overlays must not move original code or data")
    runs = []
    for i in diff:
        if runs and i <= runs[-1][1] + 8:
            runs[-1][1] = i
        else:
            runs.append([i, i])
    with open(sys.argv[3], "w") as out:
        out.write("/* generated by tools/recomp/romdiff.py: bytes of the patched build */\n")
        out.write('#include "rompatch.h"\n\n')
        for n, (s, e) in enumerate(runs):
            data = ", ".join(f"0x{b:02x}" for b in patched[s:e + 1])
            out.write(f"static const uint8_t run{n}[] = {{{data}}};\n")
        out.write("\nconst RomPatch rom_patches[] = {\n")
        for n, (s, e) in enumerate(runs):
            out.write(f"  {{0x{s:06x}, {e - s + 1}, run{n}}},\n")
        if not runs:
            out.write("  {0, 0, 0},\n")
        out.write("};\n")
        out.write(f"const int rom_patch_count = {len(runs)};\n")


if __name__ == "__main__":
    main()
